name: First Workflow
on: workflow_dispatch
jobs: 
  first-step:
    runs-on: ubuntu-latest
    steps: 
      - name: Print greeting
        run: echo "Hello world!"
      - name: Print goodbye
        run: echo "Goodbye world"
    
